### ISSUE TITLE
真机没有开启开发者模式的情况下，控制台里有报错

### ISSUE THREAD

**Issue by duyanguang** [meituan/lyrebird-ios#10]
Could not start screenshotr service! Remember that you have to mount the Developer disk image on your device if you want to use the screenshotr service.
Traceback (most recent call last):
  File "/Users/XXXXX/overbridge/overbridge/venv/lib/python3.6/site-packages/lyrebird/event.py", line 39, in broadcast_handler
    callback_fn(message)
  File "/Users/XXXXX/overbridge/overbridge/venv/lib/python3.6/site-packages/lyrebird_ios/ui.py", line 93, in get_screen_shot
    'name': os.path.basename(screen_shot_path),
  File "/usr/local/bin/../../../Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/posixpath.py", line 146, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not bool

**Comment by YurRee** [comment]
TypeError 异常下一个版本处理一下。
另：Could not start screenshotr service! Remember that you have to mount the Developer disk image on your device if you want to use the screenshotr service. 这个问题，你连上手机，直接在终端输入 `idevicescreenshot` 能截图么？
